### ISSUE TITLE
Restoring a Galera Cluster : 1 node is enough

### ISSUE THREAD

**Issue by ldangeard-orange** [Orange-OpenSource/galera-operator#10]
When operatoir restore a Galera Cluster, ir restore `MariaBackup` backup on all nodes of the cluster.

This is of no interest, because after the bootstrap of the 1st node, the other nodes are not able to provide the last number of trasanction galera realize. 
There is automatically a synchronization of the node via SST.

So just restore on first node (bootstrap)

**Comment by sebs42** [comment]
I understand your point of view but doing the restore process like this is today the best solution, because it is faster but also, the operator just starts x standalone instances and it will no do anything until datas are copied. If some standalone instance crashed or were killed during the restore process, it will not stop the restore process. If we have at least one running instance, the Galera cluster can be started.
