### ISSUE TITLE
publish on operatorhub.io 

### ISSUE THREAD

**Issue by Jacq** [Orange-OpenSource/galera-operator#16]
Hi,
I did not find info about the maturity of this operator, is it safe to run in production environments?
Have you consider to publish it in operatorhub.io?, thanks!
Cheers,
Jacq

**Comment by sebs42** [comment]
Hi Jacq,
this operator is a beta release as describe in the documentation. We are not providing any support if your run it in production, this is not a commercial product nor a product with a support that can be buyed. We developed several operators in Orange for our needs and we open sourced some of them like this one.
About the publication on operatorhub.io, it can be done, but it need to be packaged to be managed by olm (operator lifecycle manager) and today I personally have no time to do this because it is not mandatory to run it on a vanilla K8S cluster. It is if you want to use operator catalog, and it is available per default on Openshift 4.x. If you want to contribue and dot this part - including testing -, feel free.
Regards,
Sébastien

**Comment by Jacq** [comment]
Thanks for the info, and for the operator!
Regards,
Jacq
